name: covidapp_flutter
description: 'A new Flutter project. Created by Slidy'

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.5
  intl: ^0.16.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Bebas-Regular
      fonts:
        - asset: assets/fonts/Bebas-Regular.ttf 
  
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'